### PR TITLE
WIP: update for CSTParser:noval

### PR DESCRIPTION
**Pull request by ZacLN**

### CODE REVIEW

**Comment by davidanthoff** [comment]
Hm, not clear to me why the windows build fails the tests... Any idea?

**Comment by ZacLN** [comment]
Nope no idea, I'll try and test this on a windows set up this weekend

**Comment by ZacLN** [comment]
Eek, this is failing on my own setup, it's a CSTParser issue with incorrect `fullspan`s

**Comment by ZacLN** [comment]
I've pushed what I hope is a fix to CSTParser and bumped the version here, this should pass when METADATA is updated

**Pull request merged**
