### PR TITLE
Added instructions for setting up neovim

### PR DESCRIPTION
**Pull request by joshbode**

### CODE REVIEW

**Comment by davidanthoff** [comment]
Excellent, this is really helpful! One thought: If we add all the detailed instructions/manuals for various editors to the README it will get quite long... What about this: we add a Wiki page for each editor here in this repo that has all the detailed instructions for that editor (i.e. most of the text that is in this PR), and then in the README we just add one short section that has links to all the Wiki pages for the various editors?

**Comment by joshbode** [comment]
I think that makes sense - is the wiki activated?
Seems to just jump back to the main repo page.

**Comment by davidanthoff** [comment]
It should work, I just added a page for Neovim, and I think you should be able to edit that?

**Comment by joshbode** [comment]
Thanks - I can see it now, but can't see an edit button for the page.

**Comment by davidanthoff** [comment]
Ah, wrong security setting. I think you should be able to edit it now, I just changed it.

**Comment by joshbode** [comment]
Ta! Saved, and the README has been adjusted, too.

**Comment by davidanthoff** [comment]
Excellent, thanks!

**Comment by joshbode** [comment]
No problems! I'm excited to try this out in nvim :)

**Pull request merged**
