### PR TITLE
Fixes ws offset for goto-definitions

### PR DESCRIPTION
**Pull request by ZacLN**

### CODE REVIEW

**Comment by davidanthoff** [comment]
That doesn't seem to work, it still selects too many lines, I even have the impression it is sometimes selecting more than previously?

**Comment by ZacLN** [comment]
I'm struggling to find a misalignment, could you give a couple examples so I can track this down. (Pkg, file, line, col)

There's an offset issue with documented functions that I'll fix at the same time

**Comment by davidanthoff** [comment]
Essentially every function in e.g. [this](https://github.com/davidanthoff/DataValueArrays.jl/blob/master/src/reduce.jl) file. I'm opening the whole folder as the workspace root.

Here is an example from that file:
image

One thing that is interesting: it seems it always includes the first line of the next block. Just stripping of white spaces at the end might not be the right strategy here, it seems to somehow include the next block. All the starting positions are always correct.

**Comment by ZacLN** [comment]
Ah OK j fixed the wrong thing , I'll sort it in the morning

**Comment by ZacLN** [comment]
CI failure is git related

**Comment by davidanthoff** [comment]
I get the following error with the latest version when I open the file ``primitives.jl`` in DataValueArrays.jl:
````
INFO: RECEIVED: {"jsonrpc":"2.0","id":16,"method":"textDocument/documentSymbol","params":{"textDocument":{"uri":"file:///c%3A/users/anthoff/.julia/v0.6/datavaluearrays/src/primitives.jl"}}}
INFO: 
ERROR: LoadError: MethodError: no method matching trailing_ws_length(::CSTParser.EXPR{CSTParser.LITERAL{FALSE::Tokenize.Tokens.Kind = 84}})
Closest candidates are:
  trailing_ws_length(!Matched::CSTParser.EXPR{CSTParser.IDENTIFIER}) at c:\Users\anthoff\source\julia-vscode\scripts\languageserver\packages\LanguageServer\src\provider_definitions.jl:56
  trailing_ws_length(!Matched::CSTParser.EXPR{P<:CSTParser.PUNCTUATION}) where P<:CSTParser.PUNCTUATION at c:\Users\anthoff\source\julia-vscode\scripts\languageserver\packages\LanguageServer\src\provider_definitions.jl:60
  trailing_ws_length(!Matched::CSTParser.EXPR{K<:CSTParser.KEYWORD{T}}) where {T, K<:CSTParser.KEYWORD{T}} at c:\Users\anthoff\source\julia-vscode\scripts\languageserver\packages\LanguageServer\src\provider_definitions.jl:64
Stacktrace:
 [1] process(::LanguageServer.JSONRPC.Request{Val{Symbol("textDocument/documentSymbol")},LanguageServer.DocumentSymbolParams}, ::LanguageServer.LanguageServerInstance) at c:\Users\anthoff\source\julia-vscode\scripts\languageserver\packages\LanguageServer\src\provider_symbols.jl:13
 [2] run(::LanguageServer.LanguageServerInstance) at c:\Users\anthoff\source\julia-vscode\scripts\languageserver\packages\LanguageServer\src\languageserverinstance.jl:44
 [3] include_from_node1(::String) at .\loading.jl:569
 [4] include(::String) at .\sysimg.jl:14
 [5] process_options(::Base.JLOptions) at .\client.jl:305
 [6] _start() at .\client.jl:371
while loading c:\Users\anthoff\source\julia-vscode\scripts\languageserver\main.jl, in expression starting on line 27
[Info  - 9:27:16 AM] Connection to server got closed. Server will restart.
````

**Comment by ZacLN** [comment]
OK that should cover all cases

**Pull request merged**
