### PR TITLE
Add `end` completion

### PR DESCRIPTION
**Pull request by ZacLN**

### CODE REVIEW

**Comment by andyferris** [comment]
Will this decrement indentation of `end` automatically as I type it?

**Comment by ZacLN** [comment]
At the moment in vscode de-indenting occurs on hitting enter (after `end`, `else`, etc.)

**Comment by andyferris** [comment]
OK, I see that now. This will become more obvious after this fix :)

**Comment by davidanthoff** [comment]
@andyferris If you want to add another voice over at the VS Code repo to fix this properly, here is the issue: Microsoft/vscode#2272.

**Comment by andyferris** [comment]
Done.

**Pull request merged**
