### PR TITLE
transfer full doc text on change

### PR DESCRIPTION
**Pull request by ZacLN**
This should fix [this](https://github.com/JuliaEditorSupport/julia-vscode/issues/188), and incremental text update is not needed until incremental parsing returns

### CODE REVIEW

**Comment by davidanthoff** [comment]
Should we publish a bug fix release 0.6.1 with this?

**Comment by ZacLN** [comment]
Yep, that bug was pretty major

**Comment by davidanthoff** [comment]
There is still something wrong. When I open a file now and type, it moves all the green underlines for diagnostics in the rest of the file around while I type.

**Comment by ZacLN** [comment]
I can't work out what's getting confused here and I'm not going to have enough time to dig into it for a few days, Want to revert this so that at least master works as before?

**Comment by davidanthoff** [comment]
Alright, I revert this for now.

**Pull request merged**
